// This file is autogenerated, do not try to change it manually
package com.paijan.pcpilot.utils

object Constants {
    const val KEEP_ALIVE_SEND_RATE_MS : Long = 500
    const val KEEP_ALIVE_TIMEOUT_MS : Long = KEEP_ALIVE_SEND_RATE_MS * 6
    const val MANUAL_LOOP_BACK_RATE_MS : Long = 100
    const val SERVER_LIST_MAX_AGE_MS : Long = 6000
    const val MAX_MESSAGE_SIZE : Int = 128
}
