macro(add_sources)
	set_property(GLOBAL APPEND PROPERTY ${SOURCE_FILES_PROPERTY} ${ARGN})
endmacro()

macro(get_sources var)
	get_property(${var} GLOBAL PROPERTY ${SOURCE_FILES_PROPERTY})
endmacro()
	
macro(add_subdirectories)
	foreach(subdir ${ARGN})
		add_subdirectory(${subdir})
	endforeach()
endmacro()

macro(add_os_specific_subdirectory)
	if (WIN32)
		add_subdirectory("windows")
	else()
		message(FATAL_ERROR "Not supported OS")
	endif()
endmacro()

macro(handle_library_dependencies)
	if (WIN32)
		target_link_libraries(${PROJECT_NAME} WS2_32.lib Iphlpapi.lib)
	else()
		message(FATAL_ERROR "Not supported OS")
	endif()
endmacro()