// This file is autogenerated, do not try to change it manually
package com.paijan.pcpilot

object Constants {
    const val KEEP_ALIVE_SEND_RATE_MS : Float = 500.0f
    const val KEEP_ALIVE_TIMEOUT_MS : Float = KEEP_ALIVE_SEND_RATE_MS * 4
    const val MAX_MESSAGE_SIZE : Int = 128
}
