// This file is autogenerated, do not try to change it manually
#pragma once

#include "Communication/InetAddress.h"

template <typename DerivingClass, unsigned int SIZE>
class Message {
public:
    using Byte = unsigned char;

protected:
    Byte bytes[SIZE];
    Message() {}
    Message(Byte *bytes) {
        std::memcpy(this->bytes, bytes, SIZE);
    }

    template <typename T, int offset>
    T getField() {
        static_assert(offset + sizeof(T) - 1 < SIZE, "invalid offset");
        T result;
        std::memcpy(&result, this->bytes + offset, sizeof(T));
        return result;
    }

    template <typename T, int offset>
    DerivingClass& setField(T field) {
        static_assert(offset + sizeof(T) - 1 < SIZE, "invalid offset");
        std::memcpy(this->bytes + offset, &field, sizeof(T));
        return *static_cast<DerivingClass*>(this);
    }

    DerivingClass& setPreamble() {
        static const std::string field = "PCPILOT";
        std::memcpy(this->bytes + 0, &field.front(), 7);
        return *static_cast<DerivingClass*>(this);
    }
};


class ServerMessage : public Message<ServerMessage, 16> {
private:
    InetAddress senderAddress;
    ServerMessage() : ServerMessage({ 0, 0 }) {}
    ServerMessage(const InetAddress &senderAddress) : senderAddress(senderAddress) {}
public:
    enum class Type : Byte {
        ConnectionRequest = 0,
        KeepAlive = 1,
        MoveCursor = 2,
        LeftPress = 3,
        LeftRelease = 4
    };

    Type getType() {
        return static_cast<Type>(getField<Byte, 0>());
    }

    // --- --- --- ConnectionRequest
    static ServerMessage createMessageConnectionRequest() {
        return ServerMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::ConnectionRequest));
    }

    // --- --- --- KeepAlive
    static ServerMessage createMessageKeepAlive() {
        return ServerMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::KeepAlive));
    }

    // --- --- --- MoveCursor
    static ServerMessage createMessageMoveCursor(float x, float y) {
        return ServerMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::MoveCursor))
            .setField<float, 8>(x)
            .setField<float, 12>(y);
    }
    float getMessageMoveCursorX() {
        return getField<float, 8>();
    }
    float getMessageMoveCursorY() {
        return getField<float, 12>();
    }

    // --- --- --- LeftPress
    static ServerMessage createMessageLeftPress() {
        return ServerMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::LeftPress));
    }

    // --- --- --- LeftRelease
    static ServerMessage createMessageLeftRelease() {
        return ServerMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::LeftRelease));
    }
};



class ClientMessage : public Message<ClientMessage, 8> {
public:
    enum class Type : Byte {
        ConnectionAccept = 0,
        KeepAlive = 1
    };

    Type getType() {
        return static_cast<Type>(getField<Byte, 0>());
    }

    // --- --- --- ConnectionAccept
    static ClientMessage createMessageConnectionAccept() {
        return ClientMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::ConnectionAccept));
    }

    // --- --- --- KeepAlive
    static ClientMessage createMessageKeepAlive() {
        return ClientMessage()
            .setPreamble()
            .setField<Byte, 7>(static_cast<Byte>(Type::KeepAlive));
    }
};


