<%! import utils.definitions as definitions%>\
// This file is autogenerated, do not try to change it manually
#pragma once

namespace Constants {
% for constant in constants:
    ${utils.get_constant_specifiers(constant.type)}${constant.type.name_cpp} ${constant.name} = ${utils.get_constant_value(constant)};
% endfor
}
