// This file is autogenerated, do not try to change it manually
#pragma once

namespace Constants {
    constexpr long KEEP_ALIVE_SEND_RATE_MS = 500;
    constexpr long KEEP_ALIVE_TIMEOUT_MS = KEEP_ALIVE_SEND_RATE_MS * 6;
    constexpr long MANUAL_LOOP_BACK_RATE_MS = 100;
    constexpr long SERVER_LIST_MAX_AGE_MS = 6000;
    constexpr int MAX_MESSAGE_SIZE = 128;
}
