// This file is autogenerated, do not try to change it manually
#pragma once

namespace Constants {
    const long KEEP_ALIVE_SEND_RATE_MS = 500;
    const long KEEP_ALIVE_TIMEOUT_MS = KEEP_ALIVE_SEND_RATE_MS * 4;
    const long MANUAL_LOOP_BACK_RATE_MS = 100;
    const int MAX_MESSAGE_SIZE = 128;
}
