// This file is autogenerated, do not try to change it manually
#pragma once

namespace Constants {
    const float KEEP_ALIVE_SEND_RATE_MS = 500.0f;
    const float KEEP_ALIVE_TIMEOUT_MS = KEEP_ALIVE_SEND_RATE_MS * 4;
    const int MAX_MESSAGE_SIZE = 128;
}
